main: io.github.kekdrick.ScoutingDevice.Main
name: Scouting-Device
version: 1.0
author: Kekdrick

commands:
  scoutdevice:
    usage: /scoutdevice <amount>
    permission: scoutdevice.admin

permissions:
  scoutdevice.admin:
    description: User may spawn Scout Devices and distribute to other players.
    default: op